### ISSUE TITLE
SearchPlugin is not a function 

### ISSUE THREAD

**Issue by amritnagi** [Stuyk/vitepress-plugin-simple-search#2]
Just trying this out and when I try and run it, I get the following??

```npm run docs:dev

> ***********@1.0.0 docs:dev
> vitepress dev docs

vitepress v1.0.0-alpha.17
failed to load config from C:\******\docs\vite.config.js
failed to start server. error:
 TypeError: (0 , import_vitepress_plugin_simple_search.SearchPlugin) is not a function      
    at Object.<anonymous> (C:\******\docs\vite.config.js:28:68)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object._require.extensions.<computed> [as .js] (file:///C:/******/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:63514:24)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadConfigFromBundledFile (file:///C:/******/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:63522:21)
    at loadConfigFromFile (file:///C:/******/node_modules/vite/dist/node/chunks/dep-6b3a5aff.js:63381:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

The config is just copied and pasted from the readme.

```
import { SearchPlugin } from "vitepress-plugin-simple-search";
import { defineConfig } from "vite";

export default defineConfig({
  plugins: [SearchPlugin()],
});

```

**Comment by Stuyk** [comment]
Try importing with...

import * as SearchPlugin

Then log SearchPlugin and see what pathways are available. Then adjust the import accordingly. 

I am currently using Node17 with this and my other repository athena-docs-vitepress hasn't had any issues with it. Might help you resolve the issue by doing a quick cross comparison of the config files.

**Comment by amritnagi** [comment]
Checked the athena repo and noticed it should be `SimpleSearch()`  - so have raised a PR to update the readme! :)

Thanks for creating this! :)
